quarkus:

  http:
    cors: true
    host: 0.0.0.0

  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

  hibernate-orm:
    database:
      generation: drop-and-create
    log:
      sql: true

  smallrye-openapi:
    path: /openapi
    info:
      title: "CRUD API"
      version: "1.0.0"
  swagger-ui:
    always-include: true
    path: /swagger-ui

quarkus:
  log:
    level: INFO
    category:
      "com.dqmdz":
        level: DEBUG
      "com.fasterxml.jackson":
        level: DEBUG
      "io.quarkus":
        level: INFO
      "org.hibernate":
        level: INFO
    console:
      format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
      level: DEBUG
  console:
    json: false